/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "status-success": "#1B7A43",
        "outline": "#737780",
        "on-primary-container": "#799dd6",
        "gov-saffron": "#FF8514",
        "status-warning": "#B45309",
        "surface-container-highest": "#d8e3fb",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "on-background": "#111c2d",
        "surface-dim": "#cfdaf2",
        "surface-container-low": "#f0f3ff",
        "secondary-fixed-dim": "#afc8f0",
        "surface-canvas": "#F4F6F9",
        "primary": "#001e40",
        "border-strong": "#94A3B8",
        "tertiary-fixed-dim": "#ffb690",
        "secondary-container": "#bdd6ff",
        "on-tertiary-fixed": "#341100",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c3c6d1",
        "tertiary-container": "#592300",
        "tertiary": "#381300",
        "text-muted": "#64748B",
        "surface-variant": "#d8e3fb",
        "inverse-surface": "#263143",
        "on-surface-variant": "#43474f",
        "border-subtle": "#CBD5E1",
        "secondary": "#476083",
        "on-error-container": "#93000a",
        "surface-tint": "#3a5f94",
        "on-tertiary-container": "#d8885c",
        "surface": "#f9f9ff",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "on-secondary-fixed-variant": "#2f486a",
        "primary-fixed": "#d5e3ff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#1f477b",
        "error": "#ba1a1a",
        "secondary-fixed": "#d4e3ff",
        "surface-bright": "#f9f9ff",
        "status-danger": "#B3261E",
        "text-primary": "#1E293B",
        "background": "#f9f9ff",
        "on-secondary-fixed": "#001c3a",
        "status-info": "#003366",
        "on-surface": "#111c2d",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#723610",
        "on-error": "#ffffff",
        "surface-container": "#e7eeff",
        "inverse-primary": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#445d80",
        "surface-card": "#FFFFFF",
        "text-secondary": "#4B5563",
        "primary-fixed-dim": "#a7c8ff",
        "primary-container": "#003366"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "space-base": "1rem",
        "space-md": "0.75rem",
        "gutter-mobile": "1rem",
        "container-max": "1280px",
        "space-2xl": "3rem"
      },
      fontFamily: {
        "display-lg": ["Noto Sans", "sans-serif"],
        "headline-sm": ["Noto Sans", "sans-serif"],
        "label-lg": ["Noto Sans", "sans-serif"],
        "body-sm": ["Noto Sans", "sans-serif"],
        "body-lg": ["Noto Sans", "sans-serif"],
        "display-lg-mobile": ["Noto Sans", "sans-serif"],
        "headline-lg-mobile": ["Noto Sans", "sans-serif"],
        "body-md": ["Noto Sans", "sans-serif"],
        "headline-md": ["Noto Sans", "sans-serif"],
        "title-md": ["Noto Sans", "sans-serif"],
        "label-md": ["Noto Sans", "sans-serif"],
        "headline-lg": ["Noto Sans", "sans-serif"],
        "label-sm": ["Noto Sans", "sans-serif"]
      }
    }
  },
  plugins: [],
};
